[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = ".netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888

[[plugins]]
  package = "@netlify/plugin-nextjs" 